package com.example.core.demo

import com.example.core.demo.model.DemoAvailabilityDay
import com.example.core.demo.model.DemoItem
import com.example.core.demo.model.DemoItemStatus

object DemoItems {

    private val defaultAvailability = listOf(
        DemoAvailabilityDay(date = "2026-05-08", isAvailable = true),
        DemoAvailabilityDay(date = "2026-05-09", isAvailable = true),
        DemoAvailabilityDay(date = "2026-05-10", isAvailable = false),
        DemoAvailabilityDay(date = "2026-05-11", isAvailable = false),
        DemoAvailabilityDay(date = "2026-05-12", isAvailable = true),
        DemoAvailabilityDay(date = "2026-05-13", isAvailable = true),
        DemoAvailabilityDay(date = "2026-05-14", isAvailable = false),
        DemoAvailabilityDay(date = "2026-05-15", isAvailable = true)
    )

    val all = listOf(
        DemoItem(
            id = DemoIds.ITEM_POCOFON_ID,
            ownerId = DemoIds.OWNER_IVAN_ID,
            categoryId = DemoIds.CATEGORY_ELECTRONICS_ID,
            title = "Pocofon F3 Pro",
            description = "Смартфон в хорошем состоянии, подойдёт для поездки или временного использования.",
            pricePerDay = 999,
            pricePerHour = 150,
            depositAmount = 5000,
            city = "Новосибирск",
            pickupLocation = "ул. Ленина, 10",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 43,
            imageKey = "pocofon",
            photoKeys = listOf("pocofon", "pocofon", "pocofon"),
            isFavorite = true,
            createdAt = "2026-04-28T09:59:44.133Z",
            updatedAt = "2026-04-28T09:59:44.133Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_ISU_ID,
            ownerId = DemoIds.OWNER_ALEXEY_ID,
            categoryId = DemoIds.CATEGORY_TRANSPORT_ID,
            title = "Ису-152",
            description = "Коллекционный экземпляр для фотосессий и мероприятий.",
            pricePerDay = 100000,
            pricePerHour = null,
            depositAmount = 300000,
            city = "Новосибирск",
            pickupLocation = "площадка у музея техники",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 128,
            imageKey = "isu152",
            photoKeys = listOf("isu152", "isu152"),
            isFavorite = false,
            createdAt = "2026-04-25T12:20:00.000Z",
            updatedAt = "2026-04-25T12:20:00.000Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_CAR_ID,
            ownerId = DemoIds.OWNER_SERGEY_ID,
            categoryId = DemoIds.CATEGORY_TRANSPORT_ID,
            title = "Автомобиль Volkswagen 2018 год",
            description = "Автомобиль для краткосрочной аренды.",
            pricePerDay = 10000,
            pricePerHour = 900,
            depositAmount = 30000,
            city = "Новосибирск",
            pickupLocation = "ул. Советская, 31",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 76,
            imageKey = "wolksvagencar",
            photoKeys = listOf("wolksvagencar", "wolksvagencar"),
            isFavorite = false,
            createdAt = "2026-04-21T08:10:00.000Z",
            updatedAt = "2026-04-21T08:10:00.000Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_SOUP_ID,
            ownerId = DemoIds.OWNER_MARIA_ID,
            categoryId = DemoIds.CATEGORY_HOME_ID,
            title = "Кастрюля для супа",
            description = "Большая кастрюля для готовки на компанию.",
            pricePerDay = 100,
            pricePerHour = null,
            depositAmount = 500,
            city = "Новосибирск",
            pickupLocation = "ул. Кирова, 7",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 19,
            imageKey = "soup",
            photoKeys = listOf("soup", "soup"),
            isFavorite = false,
            createdAt = "2026-04-18T14:35:00.000Z",
            updatedAt = "2026-04-18T14:35:00.000Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_BIKE_ID,
            ownerId = DemoIds.OWNER_DMITRY_ID,
            categoryId = DemoIds.CATEGORY_SPORT_ID,
            title = "Велосипед горный",
            description = "Подойдёт для прогулок и пересечённой местности.",
            pricePerDay = 700,
            pricePerHour = 120,
            depositAmount = 3000,
            city = "Новосибирск",
            pickupLocation = "ул. Красный проспект, 55",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 54,
            imageKey = "bike",
            photoKeys = listOf("bike", "bike"),
            isFavorite = false,
            createdAt = "2026-04-16T10:00:00.000Z",
            updatedAt = "2026-04-16T10:00:00.000Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_CANON_ID,
            ownerId = DemoIds.OWNER_MARIA_ID,
            categoryId = DemoIds.CATEGORY_PHOTO_VIDEO_ID,
            title = "Фотоаппарат Canon EOS 250D",
            description = "Фотоаппарат для съёмки мероприятий, прогулок и контента.",
            pricePerDay = 5000,
            pricePerHour = 900,
            depositAmount = 15000,
            city = "Астана",
            pickupLocation = "центр города",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 91,
            imageKey = "camera",
            photoKeys = listOf("camera", "camera"),
            isFavorite = true,
            createdAt = "2026-04-20T13:09:00.000Z",
            updatedAt = "2026-04-20T13:09:00.000Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_DRILL_ID,
            ownerId = DemoIds.OWNER_DMITRY_ID,
            categoryId = DemoIds.CATEGORY_TOOLS_ID,
            title = "Дрель Bosch Professional",
            description = "Дрель для ремонта, сверления дерева, металла и бетона.",
            pricePerDay = 2000,
            pricePerHour = 350,
            depositAmount = 6000,
            city = "Алматы",
            pickupLocation = "район Бостандык",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 65,
            imageKey = "drill",
            photoKeys = listOf("drill"),
            isFavorite = true,
            createdAt = "2026-04-22T10:42:00.000Z",
            updatedAt = "2026-04-22T10:42:00.000Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_TENT_ID,
            ownerId = DemoIds.CURRENT_USER_ID,
            categoryId = DemoIds.CATEGORY_SPORT_ID,
            title = "Палатка туристическая на 4 места",
            description = "Палатка для поездки на природу, подходит для компании до 4 человек.",
            pricePerDay = 1500,
            pricePerHour = null,
            depositAmount = 5000,
            city = "Новосибирск",
            pickupLocation = "Академгородок",
            status = DemoItemStatus.ACTIVE,
            moderationComment = null,
            viewsCount = 37,
            imageKey = "tent",
            photoKeys = listOf("tent"),
            isFavorite = false,
            createdAt = "2026-04-10T12:00:00.000Z",
            updatedAt = "2026-04-21T12:00:00.000Z",
            availability = defaultAvailability
        ),
        DemoItem(
            id = DemoIds.ITEM_MAKITA_ID,
            ownerId = DemoIds.CURRENT_USER_ID,
            categoryId = DemoIds.CATEGORY_TOOLS_ID,
            title = "Шуруповёрт Makita",
            description = "Шуруповёрт с двумя аккумуляторами и набором бит.",
            pricePerDay = 1200,
            pricePerHour = 250,
            depositAmount = 4000,
            city = "Новосибирск",
            pickupLocation = "ул. Фрунзе, 20",
            status = DemoItemStatus.MODERATION,
            moderationComment = null,
            viewsCount = 12,
            imageKey = "makita",
            photoKeys = listOf("makita"),
            isFavorite = false,
            createdAt = "2026-04-29T10:00:00.000Z",
            updatedAt = "2026-04-29T10:00:00.000Z",
            availability = defaultAvailability
        )
    )
}